version: '3'
services:
  recorder:
    image: robotastic/trunk-recorder:latest
    container_name: trunk-recorder
    restart: always
    privileged: true
    logging:
        options:
             {'max-size':'10m', 'max-file':'5'}
    volumes:
      - /var/run/dbus:/var/run/dbus 
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket 
      - /home/radio/trunk-recorder:/app
      - /etc/localtime:/etc/localtime:ro
